### ISSUE TITLE
32kbps OGG vs. 128kbps OGG

### ISSUE THREAD

**Issue by npmussi** [SHNecro/ShanghaiEXE#10]
Should the current music files be replaced by the 128kbps variants? It would significantly upgrade the music quality, and the looping still works properly with no issues.

The .ogg files are in these Dropboxes:
https://www.dropbox.com/sh/ez86vg9ojgr3hp0/AACxOayOjT6FA-aS34uLkF8va?dl=0
https://www.dropbox.com/sh/kmi3sl26utl9gf4/AABxMtVIiG-8fjDEqBlRqzcVa?dl=0

**Comment by npmussi** [comment]
The OGG files are in these two Dropboxes:
https://www.dropbox.com/sh/kmi3sl26utl9gf4/AABxMtVIiG-8fjDEqBlRqzcVa?dl=0
https://www.dropbox.com/sh/ez86vg9ojgr3hp0/AACxOayOjT6FA-aS34uLkF8va?dl=0

**Comment by SHNecro** [comment]
Nice find, they also included the BGM for the final battle and final area which I've added in as well.
Bumps overall game size to ~130 MB, but it's 2019, it shouldn't be a problem
