### ISSUE TITLE
End Game

### ISSUE THREAD

**Issue by Coyote133** [SHNecro/ShanghaiEXE#17]
I was in the part whenI need to get to the deepest part of the undernet, and when I get to undernet 7, I talked to a mr prog (?) that said me that it was the end of the demo, but I read that this version reaches the final boss
![end game](https://user-images.githubusercontent.com/59122111/71328318-562a2480-24e3-11ea-939d-a05a9110717e.PNG)

**Comment by SHNecro** [comment]
Fixed, forgot to set that sprite to only appear when actually at the end of the demo.

You can continue playing, that area is just a dead end at the moment, try going another direction.
