### ISSUE TITLE
Final Boss

### ISSUE THREAD

**Issue by Coyote133** [SHNecro/ShanghaiEXE#19]
Is there a way to re fight the final boss of the game?

**Comment by SHNecro** [comment]
There is a demo room accessible through Alice's HP, which has the original challenge gauntlets and refightable versions of certain story bosses, unimplemented bosses, and bosses which were teased but not coded, added by another anon.

This used to be mentioned by the sprite that blocked off the unfinished content, but that's been removed. I'll find some other place to put it in.
