### ISSUE TITLE
"Tension" music continues to play after completing Utsuho sidequest

### ISSUE THREAD

**Issue by doicm** [SHNecro/ShanghaiEXE#21]
I finished the game, and then I did the Utsuho sidequest afterwards. I finished it, but in the real world the "tension" music (I don't know the actual title) continues playing in everywhere but the hospital. Not sure how to fix, but may be an issue where a music flag is set incorrectly.

**Comment by SHNecro** [comment]
Fixed, replaced use of BGM override flag with a local BGM override since you can't leave that single overworld room during the event anyways.
