### ISSUE TITLE
Game will crash at random when fighting YuyukoSP5

### ISSUE THREAD

**Issue by Inviting** [SHNecro/ShanghaiEXE#22]
Only happens when Yuyuko is able to move (not in hitstun/paralysis), but I can't find out what she's trying to do that crashes the game. Happens at random. Her HP doesn't seem to matter.

**Comment by SHNecro** [comment]
Can't seem to replicate this but haven't been able to test too thoroughly, just sitting there with debug invis and turbo/nonturbo.
Is there anything else on the field like AreaGrab, viruses, or panels?
If you post your save file I can try out suspicious combinations.

**Comment by Inviting** [comment]
No AreaGrab. It's just the Yuyuko fight in the Bonus Room with the rank boosted.
After testing some more, I've seen it happen anywhere between 900-3100 HP. 

[save.zip](https://github.com/SHNecro/ShanghaiEXE/files/4018322/save.zip)

**Comment by seerow** [comment]
Is the crash during the Barrage attack? That one does things with the movement code.

**Comment by SHNecro** [comment]
Fixed an issue (locally, not yet pushed), not sure if it's the one you're seeing.
If Yuyuko had Gravity/Heavy on a sand panel, the "do not move to same panel" logic would go into an infinite loop.
That's a freeze rather than a crash so I'm not sure, but there might be something that ends/stalls programs stuck in an infinite loop.

**Comment by Inviting** [comment]
That might be the problem! The game would get stuck and eventually stop responding, usually some time after I performed a combo. I'll try taking the MedusaEyes out of my deck and see if that solves it.

**Comment by Inviting** [comment]
That was the problem. I haven't seen a freeze since.
