### ISSUE TITLE
Kikuri will adopt Iku's name, movement speed, and HP values when her rank is changed.

### ISSUE THREAD

**Issue by Inviting** [SHNecro/ShanghaiEXE#23]
This is the same thing that was happening with Mima and Marisa, earlier. This only applies to regular Kikuri, and not KikuriHM.

![image](https://user-images.githubusercontent.com/59452249/71777705-b481e900-2f60-11ea-89a9-6a2eb38d0414.png)

Sorry if this is already known - I didn't see anyone mentioning it.

**Comment by SHNecro** [comment]
Fixed in _2, removed other versions besides regular and HM since there's no scaling implemented.
