### ISSUE TITLE
DruidManX ID Placement

### ISSUE THREAD

**Issue by BigCti** [SHNecro/ShanghaiEXE#24]
Small issue, but DruidManX is listed at the very end when ordering by ID, after VirusBall2, instead of after DruidManV3 like it should be.
![image](https://user-images.githubusercontent.com/57572511/72033951-58b5a980-3259-11ea-82bc-076c460564dd.png)

**Comment by SHNecro** [comment]
Thanks, learned that illegal chips also have a "sortnumber" field that handles stuff like this.

Fixed in source but since it's minor it'll wait until next release.
