### ISSUE TITLE
My mess of code

### ISSUE THREAD

**Issue by seerow** [SHNecro/ShanghaiEXE#5]
Unfortunately I don't know how to use Git or Github very well or I could make an attempt at reconciling it with your code, but regardless, here's a link to it.

https://mega.nz/#!EQhDkayI!pO2AJF4hW6aWlmcg-jjjsqV2-u_yheMFsMi4bGZ08gA

Has two main directories, one with just the stuff you likely want to mess around with alongside the graphical edits I was working on, the other a more messy set of the set of your decomp source I was using and the python scripts/graphics in a bit of an unorganized manner I used. 

Later I may try to write up an explanation of what I know about the Enemy, Chip, and Attack code to try and make this headache more manageable. With attempting to integrate this into what you've got, I'd suggest you start out putting the modified DS graphics in and some of the chips they are for to see that it works out. If you want to try playing it to see the (unfinished) state the stuff was in my save and compiled game is in \Code not inside the project files\ShanghaiEXE\Rel test

**Comment by SHNecro** [comment]
Good stuff, just made a preliminary commit integrating the bosses and chips.

Any preference on credits?

**Comment by seerow** [comment]
No strong preference.
