### ISSUE TITLE
Mystery data is not displayed in Japanese

### ISSUE THREAD

**Issue by pa-me** [SHNecro/ShanghaiEXE#6]
hi.
If it is Japanese ver, the details are not displayed when the mystery data is acquired.
"バトルチップ" or "null" is displayed in my environment.
This happens in both the latest build and the release version.
![image](https://user-images.githubusercontent.com/57421766/68257560-07c9df00-0077-11ea-89c7-17b32c9570b4.png)

**Comment by SHNecro** [comment]
Fixed, was a silly issue in the language files accidentally putting {0} instead of {0},{1}, so the category of item (or blank) was the only thing printed, and in the itemname slot.

Also fixed missing "Regular Memory increased,by {0} MB!", essentially just forgot a print statement.
