### ISSUE TITLE
Mima versions above V1 use Marisa's HP values/name

### ISSUE THREAD

**Issue by BigCti** [SHNecro/ShanghaiEXE#7]
Exactly what it says in the title. Not sure if this is known already, but I've tested it with every single version above V1 (but only took screenshots of V2-SP) and they all have the same issue. Everything else about the fight seems to work fine, though I haven't tested damage values to see if they're taken from Marisa as well.

![image](https://user-images.githubusercontent.com/57572511/68534578-ad8d8000-02fb-11ea-837d-65176090de8a.png)

![image](https://user-images.githubusercontent.com/57572511/68534589-d877d400-02fb-11ea-84f0-aacf4562ddee.png)

![image](https://user-images.githubusercontent.com/57572511/68534618-09f09f80-02fc-11ea-9213-36ef7d9e78b5.png)

**Comment by SHNecro** [comment]
Updated release to _1, made some adjustments.

Fixed the obvious naming and coloration problems, but I haven't playtested the new HP values I bumped up past the default Marisa values.
I'll hold off on that until adding the content using Mima, right now she's just in the debug area.
