### ISSUE TITLE
2 bugs I found

### ISSUE THREAD

**Issue by KyuJuEX099** [SHNecro/ShanghaiEXE#9]
1. Medicine X chip cause to freeze the game and then crashes. 8 out of 10 chances the freeze will happen at the exact moment when the poison ball landed on the enemies.

2. The "SELECT" button isn't working in some places. I can't put on a Regular/REG chip in my folder. And I can't delete the pet viruses. But the START+SELECT does work.

**Comment by SHNecro** [comment]
1. Fixed, for some reason the random poison bursts would make a list of 18 spots, then rely on some random part of the code to make sure it's not asking for a 19th. Added check inside the bursts themselves.

2. Can't reproduce this, I could set regular chips and release viruses normally and in turbo mode.
Actually found and fixed a bunch of crashes in the nightmare that is the virus manager having to do with moving released viruses, but select always worked.

**Comment by KyuJuEX099** [comment]
I think I know the problem regarding to the Select button. The Select button only works when it's assigned to the Space Bar. When it assigned to any other keys on keyboard. It doesn't work at all.

My assigned Select button was always the Backspace, till version 0.502e13. But not anymore in this current version.

**Comment by SHNecro** [comment]
Thanks, found and fixed, will probably make another release in a bit.
For some reason the input library has values for both Back and Backspace, so it would register Back, add it to "has just been pressed down", then register Backspace, and remove it.
